myproject/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog_page'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog-single/<str:name>',views.blog_single,name='blog-single'),

]

myproject/main_page/urls.py
from django.urls import path
from . import views
app_name = 'main_page'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('product/<str:name>', views.product_single, name='product_single'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('about/', views.about, name='about'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
    path('contact/', views.contact, name='contact'),
    path('order_succes/', views.order_succes, name='order_succes'),

]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('blog/', include('blog.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(verbose_name="ім`я",max_length=15)

    def __str__(self):
        return self.name

    def category_count(self):
        return self.blogs_set.count()


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Назва')
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if self.name and not self.name.startswith('#'):
            self.name = f'#{self.name}'

        if not self.slug:
            self.slug = slugify(self.name.lstrip('#'))

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'



class User(models.Model):
    name = models.CharField(verbose_name="ім`я",max_length=15)
    desc = models.TextField(verbose_name='опис',max_length=400)

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey('Blogs', on_delete=models.CASCADE, related_name='comments',blank=True, null=True)
    name = models.CharField(verbose_name="ім'я користовувача",max_length=30)
    email = models.EmailField(verbose_name='почта')
    image = models.ImageField(blank=True, null=True,verbose_name='фото')
    desc = models.TextField(blank=True, null=True,verbose_name='опис')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Blogs(models.Model):
    name_text = models.CharField(verbose_name='назва блогу', max_length=70)
    desc = models.TextField(verbose_name='опис не повний')
    desc_all = models.TextField(verbose_name='опис повний',blank=True)
    comment = models.ManyToManyField(Comment,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)
    img = models.ImageField(verbose_name='картинка', blank=True, null=True)
    category = models.ManyToManyField(Category)

    def comment_count(self):
        return self.comment.count()



    def __str__(self):
        return self.name_text

myproject/blog/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import SearchForm
from main_page.models import Gallery
from .models import Blogs, Tag, Category, Comment


def blog_single(request,name):
    post = get_object_or_404(Blogs, name_text=name)
    blog = Blogs.objects.all()
    category = Category.objects.all()
    tag = Tag.objects.all()
    latest_blogs = Blogs.objects.order_by('-date')[:3]

    category_filter = request.GET.get('category', None)
    tag_filter = request.GET.get('tag', None)

    if category_filter:
        blog = blog.filter(category__id=category_filter)

    if tag_filter:
        blog = blog.filter(tag__id=tag_filter)

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        image = request.FILES.get('image')
        desc = request.POST.get('message')
        if name and email and image and desc:
            comment = Comment.objects.create(name=name, email=email, image=image, desc=desc)
            post.comment.add(comment)

            return redirect('blog_page:blog-single', name=post.name_text)
    comments = post.comment.all().order_by('-date')

    gallery = Gallery.objects.all()
    context = {
        'gallery': gallery,
        'post':post,
        'blogs':blog,
        'category': category,
        'tag': tag,
        'latest_blogs': latest_blogs,
        'comments':comments
    }
    return render(request, 'html_files/blog-single.html', context)


def blog(request):

    gallery = Gallery.objects.all()
    blogs = Blogs.objects.exclude(name_text__exact='')
    tag = Tag.objects.all()
    category = Category.objects.all()

    latest_blogs = Blogs.objects.order_by('-date')[:3]

    category_filter = request.GET.get('category', None)
    tag_filter = request.GET.get('tag', None)

    if category_filter:
        blogs = blogs.filter(category__id=category_filter)

    if tag_filter:
        blogs = blogs.filter(tag__id=tag_filter)

    form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data.get('query')
        if query:
            blogs = blogs.filter(name_text__icontains=query) | blogs.filter(desc__icontains=query)

    context = {
        'gallery': gallery,
        'blogs': blogs,
        'tag': tag,
        'category': category,
        'latest_blogs': latest_blogs,
        'form': form
    }
    return render(request, 'html_files/blog.html', context)

myproject/templates/html_files/cart.html
{% extends 'html_files/base.html' %}
{% load static %}

{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'blog/images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main_page:index' %}">Home</a></span> <span>Cart</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Product</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
						    {% for o in order.all %}
							<tr class="text-center">
						        <td class="product-remove"><a href="{% url 'main_page:remove_item' item_id=o.id %}"><span class="ion-ios-close"></span></a></td>
						        
						       <td class="image-prod"><div class="img" style="background-image: url('{{ o.tovar.img.url }}');"></div></td>
						        
						        <td class="product-name">
						        	<h3>{{ o.tovar.name }}</h3>

						        </td>
						   <td class="pricing">
    <p class="price">
        {% if o.tovar.get_discounted_price != o.tovar.price %}

            <span class="price-sale">{{ o.tovar.get_discounted_price }}$</span>  
        {% else %}
            <span>{{ o.tovar.price }}$</span>  <!-- Если скидки нет -->
        {% endif %}
    </p>
</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value="{{ o.quantity}}" min="1" max="100" readonly>
					          	</div>
					          </td>
						        
						        <td class="total">{{ o.get_total }}$</td>
						      </tr>
								{% endfor %}

						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-start">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>

						<p class="d-flex">
    						<span>Subtotal</span>
    						<span>{{ total_sum }}$</span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>$0.00</span>
    					</p>
    					<p class="d-flex">
    						<span>Discount</span>
    						<span>$0.00</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>{{ total_sum }}$</span>
    					</p>

    				</div>
    				<p class="text-center"><a href="{% url 'main_page:checkout' %}" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
    			</div>
    		</div>
			</div>
		</section>
		

   <script>
		$(document).ready(function(){

		var quantitiy=0;
		   $('.quantity-right-plus').click(function(e){
		        
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		            
		            $('#quantity').val(quantity + 1);

		          
		            // Increment
		        
		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		      
		            // Increment
		            if(quantity>0){
		            $('#quantity').val(quantity - 1);
		            }
		    });
		    
		});
	</script>
{% endblock %}

myproject/templates/html_files/checkout.html
{% extends 'html_files/base.html' %}
{% load static %}

{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'blog/images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main_page:index' %}">Home</a></span> <span>Checkout</span></p>
            <h1 class="mb-0 bread">Checkout</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-10 ftco-animate">
						<form method="POST" action="{% url 'main_page:checkout' %}" class="billing-form">
    {% csrf_token %}
    <h3 class="mb-4 billing-heading">Billing Details</h3>
    <div class="row align-items-end">
        <div class="col-md-6">
            <div class="form-group">
                <label for="firstname">First Name</label>
                <input type="text" name="firstname" class="form-control" placeholder="First Name" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="lastname">Last Name</label>
                <input type="text" name="lastname" class="form-control" placeholder="Last Name" required>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="country">State / Country</label>
                <div class="select-wrap">
                    <select name="country" id="country" class="form-control" required>
                        <option value="France">France</option>
                        <option value="Italy">Italy</option>
                        <option value="Philippines">Philippines</option>
                        <option value="South Korea">South Korea</option>
                        <option value="Hongkong">Hongkong</option>
                        <option value="Japan">Japan</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="streetaddress">Street Address</label>
                <input type="text" name="streetaddress" class="form-control" placeholder="House number and street name" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <input type="text" name="apartment" class="form-control" placeholder="Apartment, suite, unit etc: (optional)">
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="towncity">Town / City</label>
                <input type="text" name="towncity" class="form-control" placeholder="Town / City" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="postcodezip">Postcode / ZIP *</label>
                <input type="text" name="postcodezip" class="form-control" placeholder="Postcode / ZIP" required>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" name="phone" class="form-control" placeholder="Phone" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="emailaddress">Email Address</label>
                <input type="email" name="emailaddress" class="form-control" placeholder="Email Address" required>
            </div>
        </div>
        <div class="w-100"></div>

        <div class="col-md-12">

        </div>
    </div>





	          <div class="row mt-5 pt-3 d-flex">
	          	<div class="col-md-6 d-flex">
	          		<div class="cart-detail cart-total bg-light p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Cart Total</h3>
	          			<p class="d-flex">
    						<span>Subtotal</span>
    						<span>{{ total_sum }}$</span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>$0.00</span>
    					</p>
    					<p class="d-flex">
    						<span>Discount</span>
    						<span>$0.00</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>{{ total_sum }}$</span>
    					</p>
								</div>
	          	</div>
	          	<div class="col-md-6">
	          		<div class="cart-detail bg-light p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Payment Method</h3>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Direct Bank Tranfer</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Check Payment</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" class="mr-2"> Paypal</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="checkbox">
											   <label><input type="checkbox" value="" class="mr-2"> I have read and accept the terms and conditions</label>
											</div>
										</div>
									</div>
									<button type="submit" class="btn btn-primary py-3 px-4">Place an order</button>
								</div>
	          	</div>
	          </div>
             </form>

          </div> <!-- .col-md-8 -->
        </div>

      </div>
    </section> <!-- .section -->
		



  <script>
		$(document).ready(function(){

		var quantitiy=0;
		   $('.quantity-right-plus').click(function(e){
		        
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		            
		            $('#quantity').val(quantity + 1);

		          
		            // Increment
		        
		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		      
		            // Increment
		            if(quantity>0){
		            $('#quantity').val(quantity - 1);
		            }
		    });
		    
		});
	</script>
    {% endblock %}

myproject/templates/html_files/contact.html
{% extends 'html_files/base.html' %}
{% load static %}
{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'blog/images/bg_6.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main_page:index' %}">Home</a></span> <span>Contact</span></p>
            <h1 class="mb-0 bread">Contact Us</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section contact-section bg-light">
      <div class="container">
      	<div class="row d-flex mb-5 contact-info">
          <div class="w-100"></div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Address:</span>{{ contact.adress }}</p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Phone:</span> <a href="tel:{{ contact.phone|cut:' ' }}">{{ contact.phone }}</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Email:</span> <a href="mailto:{{ contact.email }}">{{ contact.email }}</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Website</span> <a href="{{ contact.website }}" target="_blank">{{ contact.website }}</a></p>
	          </div>
          </div>
        </div>

          <div class="row block-9">
          <div class="col-md-6 order-md-last d-flex">
            <form action="#" method="POST" enctype="multipart/form-data" class="bg-white p-5 contact-form">
              {% csrf_token %}
                <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name" id="name" name="name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email" id="email" name="email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject" id="webiste" name="website">
              </div>
              <div class="form-group">
                <textarea name="desc" id="desc" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-md-6 d-flex">
          	<div id="map" class="bg-white"></div>
          </div>
        </div>
      </div>
    </section> 
    {% endblock %}

myproject/templates/html_files/footer.html
<section class="ftco-gallery">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-8 heading-section text-center mb-4 ftco-animate">
            <h2 class="mb-4">Follow Us On Instagram</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
          </div>
    		</div>
    	</div>

	<div class="container-fluid px-0">
    <div class="row">
        {% for gal in gallery %}
            <div class="col-md-4 col-lg-2 ftco-animate">
                <a href="{{ gal.img.url }}" class="gallery image-popup img d-flex align-items-center" style="background-image: url({{ gal.img.url }});">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
    </section>

    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Minishop</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="https://x.com/"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="https://www.facebook.com/"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="https://www.instagram.com/"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'main_page:shop' %}" class="py-2 d-block">Shop</a></li>
                <li><a href="{% url 'main_page:about' %}" class="py-2 d-block">About</a></li>
                <li><a href="{% url 'main_page:contact' %}" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">

	              <ul class="list-unstyled">

	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>

myproject/templates/html_files/nav.html
<div class="py-1 bg-black">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 1235 2355 98</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">youremail@email.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'main_page:index' %}">Minishop</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'main_page:index' %}" class="nav-link">Home</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catalog</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="{% url 'main_page:shop' %}">Shop</a>

                <a class="dropdown-item" href="{% url 'main_page:cart' %}">Cart</a>
                <a class="dropdown-item" href="{% url 'main_page:checkout' %}">Checkout</a>
              </div>
            </li>
	          <li class="nav-item"><a href="{% url 'main_page:about' %}" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="{% url 'blog_page:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="{% url 'main_page:contact' %}" class="nav-link">Contact</a></li>
	          <li class="nav-item cta cta-colored"><a href="{% url 'main_page:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>{{ cart_count }}</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->

myproject/templates/html_files/shop.html
{% extends 'html_files/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
<div class="hero-wrap hero-bread" style="background-image: url({% static 'blog/images/bg_6.jpg' %});">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main_page:index' %}">Home</a></span> <span>Shop</span></p>
        <h1 class="mb-0 bread">Shop</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <!-- Sidebar with categories -->
      <div class="col-md-4 col-lg-2">
        <div class="sidebar">
          <div class="sidebar-box-2">
            <h2 class="heading">Categories</h2>
            <div class="fancy-collapse-panel">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">{{ type1.type }}</a>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                      <ul>
                        {% for c in cat_all %}
                          <li><a href="?tag={{ c.slug }}">{{ c.name }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Product Cards -->
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
          {% for c in tovars %}
            <div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
              <div class="product d-flex flex-column h-100">
                <a href="{% url 'main_page:product_single' name=c.name %}" class="img-prod">
                  <img class="img-fluid" src="{{ c.img.url }}" alt="Product image">
                  <div class="overlay"></div>
                </a>
                <div class="text py-3 pb-4 px-3">
                  <div class="d-flex">
                    <div class="cat"><span>{{ c.tag.all|join:", " }}</span></div>
                  </div>
                  <h3><a href="{% url 'main_page:product_single' name=c.name %}">{{ c.name }}</a></h3>

                  {% with skidka=skidka_tovars|get_discount:c %}
                    {% if skidka %}
                      <div class="pricing">
                        <p class="price">
                          <span class="mr-2 price-dc">{{ c.price }}$</span>
                          <span class="price-sale">{{ skidka.price_new }}$</span>
                        </p>
                      </div>
                    {% else %}
                      <div class="pricing">
                        <p class="price"><span>{{ c.price }}$</span></p>
                      </div>
                    {% endif %}
                  {% endwith %}

                  <p class="bottom-area d-flex px-3">
                    <a href="{% url 'main_page:product_single' name=c.name %}" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
                    <a href="#" class="buy-now text-center py-2"><span>Buy now <i class="ion-ios-cart ml-1"></i></span></a>
                  </p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div> <!-- /.row -->
      </div> <!-- /.col-md-8 -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</section>

{% endblock %}